version: "3.9"
services:

  encrypt:
    container_name: encrypt-web
    image: timonier/php:nginx
    ports:
      - "80:80"
    volumes:
      - ./:/home/www-data
      - ./data-encript:/home/www-data/public/uploads
      - ./data-encript:/tmp/upload
      - ./encrypt-web-default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - "domain=localhost"
      - "PASSWORD=123456"